# Specify the version for docker-compose.yml
version: "3.8"

# add the serivces needed (postgres,go)
services:
  postgres:
    image: postgres:latest
    environment:
      DATABASE_HOST: ${DB_HOST}
      DATABASE_PORT: ${DB_PORT}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes: 
      - dbdata:/var/lib/postgresql/data
    networks:
      - learning

  app:
    build: .
    environment:
      DATABASE_HOST: ${DB_HOST}
      DATABASE_PORT: ${DB_PORT}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    env_file: 
      - .env
    depends_on:
      - "postgres"
    ports:
      - "8080:8080"
    networks:
      - learning

volumes:
  dbdata: # create the volume for persisting data.

networks:
  learning:
    driver: bridge
