swagger: '2.0'
info:
  title: Products API for Distributed Systems Discipline
  version: '1.0'
host: localhost:8080
basePath: /api/v1/products
paths:
  /filter:
    get:
      produces:
        - application/json
      tags:
        - Products
      summary: Get product by title
      parameters:
        - type: string
          description: Title of product
          name: title
          in: query
          required: true
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/entity.Product'
  /:
    get:
      produces:
        - application/json
      tags:
        - Products
      summary: List of products
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/entity.Product'
    post:
      produces:
        - application/json
      tags:
        - Products
      summary: Create/Insert a product
      parameters:
        - description: Product Create DTO
          name: Product
          in: body
          required: true
          schema:
            $ref: '#/definitions/dto.ProductCreateDTO'
      responses:
        '201':
          description: CREATED
          schema:
            $ref: '#/definitions/entity.Product'
        '400':
          description: Request without body
          schema:
            type: string
  /{id}:
    get:
      produces:
        - application/json
      tags:
        - Products
      summary: Get product by id
      parameters:
        - type: string
          description: ID of product
          name: id
          in: path
          required: true
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/entity.Product'
    put:
      produces:
        - application/json
      tags:
        - Products
      summary: Update product
      parameters:
        - type: string
          description: ID of product to update
          name: id
          in: path
          required: true
        - description: Product Update DTO
          name: Product
          in: body
          required: true
          schema:
            $ref: '#/definitions/dto.ProductUpdateDTO'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/entity.Product'
    delete:
      produces:
        - application/json
      tags:
        - Products
      summary: Delete product
      parameters:
        - type: string
          description: ID of product to delete
          name: id
          in: path
          required: true
      responses:
        '204':
          description: NO CONTENT
definitions:
  entity.Product:
    type: object
    properties:
      id:
        type: integer
      title:
        type: string
      description:
        type: string
      price:
        type: number
      quantity:
        type: integer
  dto.ProductCreateDTO:
    type: object
    properties:
      title:
        type: string
      description:
        type: string
      price:
        type: number
      quantity:
        type: integer
  dto.ProductUpdateDTO:
    type: object
    properties:
      title:
        type: string
      description:
        type: string
      price:
        type: number
      quantity:
        type: integer
